import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../children/Header.jsx";
import Footer from "../children/Footer.jsx";
import { Anton } from 'next/font/google';

const anton = Anton({
  subsets: ['latin'],
  weight: '400',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "NIHACS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col min-h-screen">
          
          <Header />

          <main className="flex-grow">
            {children}
          </main>

          <Footer />

        </div>
      </body>
    </html>
  );
}